### ISSUE TITLE
Color input being accepted and parsed with leading '#' characters in string

### ISSUE THREAD

**Issue by jartek** [bgrins/TinyColor#103]
`.isValid()` returns true for these cases

```
var color1 = tinycolor("#red").isValid();
var color2 = tinycolor("#############123456").isValid();
```

However If I add `.toString()` to those, colors I get the correct values:

```
var color1 = tinycolor("#red").toString(); // returns "red"
var color2 = tinycolor("#############123456").toString(); // returns "#123456"
```

**Comment by bgrins** [comment]
I'm guessing that [stringInputToObject](https://github.com/bgrins/TinyColor/blob/1a9a45a27d7b2253d96cbbedec380abae508beb0/tinycolor.js#L1070) is incorrectly ignoring those leading # characters.  Seems like those should be invalid.

**Comment by bgrins** [comment]
Ah, it's trimming all # characters from the left of the string: https://github.com/bgrins/TinyColor/blob/1a9a45a27d7b2253d96cbbedec380abae508beb0/tinycolor.js#L7.  That should be trimming multiple leading spaces but only one leading #

**Comment by bgrins** [comment]
Should be fixed now on the latest master
