### ISSUE TITLE
[suggestion] Get the name "tinycolor" on npmjs.com.

### ISSUE THREAD

**Issue by trusktr** [bgrins/TinyColor#112]
The current package that [is there](https://www.npmjs.com/package/tinycolor) has been collecting dust for 4 years. You can contact support@npmjs.com and ask to claim the name since your project is active. They'll put you in a process where they attempt to get a hold of the current owner of the package and ask if they'll want to let you become owner of the package. If there's no reply for NPM will automatically give you the name.

**Comment by loic-rimlink** [comment]
+1
Or change your name in bower.json/package to be consistent.

Some tools (like webjars) doesn't like it.

**Comment by bgrins** [comment]
I've seen this issue btw, and considered doing this in the past but I always held off because that package has a ton of downloads so seemed like it could be a compatibility issue.

**Comment by trusktr** [comment]
Interesting, good point, despite the fact it's published over 4 years ago!

/#!/JoePea

**Comment by kumarharsh** [comment]
Wow, the version number for that one is `0.0.1` and has 36 LOC. I think it's depended upon by some *other* more popular module, which is driving it's downloads so high...

**Comment by bgrins** [comment]
I bet the theory in https://github.com/bgrins/TinyColor/issues/112#issuecomment-166814457 is right.  Either way I don't think I'll pursue getting the name since it could cause problems for some people who are depending on the other one.
