### ISSUE TITLE
[idea] Blend function.

### ISSUE THREAD

**Issue by trusktr** [bgrins/TinyColor#114]
That's the thing I always find needing, a way to blend two colors (i.e. meet in the middle between the two colors (or some percentage)). The [`color`](https://www.npmjs.com/package/color) package some some functions you can get ideas from (specifically the [mix](https://github.com/MoOx/color/blob/0748c85fe1e0dfda8bee49f943542a7782a59d53/index.js#L298) function). :]

**Comment by trusktr** [comment]
Doh, nevermind! I see your mix function. I was looking for a header called "mix" in the Color Utilities section of the README, but there is none. That's why I missed it.

**Comment by inker** [comment]
I would like to see a function to mix multiple colors, not just two, returning the mean color.
