### ISSUE TITLE
isValid() always returns true with object input

### ISSUE THREAD

**Issue by Horray** [bgrins/TinyColor#115]
I created an object with rgb property's and invalid values:

    value = {r: 'abc', g: 'something', b: 'hello'};

I then created an if-statement checking whether it's a valid color:

if (tinycolor(value).isValid()) {
    console.log("Good :)");
} else {
    console.log("Wrong!!!");
}

No matter what values I give, I always get 'Good :)' logged. I then tried using a string instead;

value = 'rgb (abc, something, hello)';
And that gives me the correct output. If it's an invalid color, I get 'Wrong!!!', and if it's a valid color, I get 'Good :)'.

I then checked the code, and saw that `isValid()` checks for valid propertys, not values. When using rgb object, how can I check if the color is valid?

(I want values from 0 - 255, not percentage or decimal.)

**Comment by bgrins** [comment]
Looks like there's a bug with object input where we should be validating that it matches the expected input format and not just returning ok = true if it has the properties.

Regarding wanting values to be within 0 - 255 or percentage / decimal, right now we make no attempt to call those invalid to more closely match CSS behavior (for instance, `rgb(-100, 0, 1000)` is blue).  So if you are specifically wanting numeric input that fits within that range you might need to do an additional check on top of isValid() to validate that.

**Comment by bgrins** [comment]
Alright, this should be fixed by https://github.com/bgrins/TinyColor/commit/4ce20e49e3dadc1277cf27009366e5c6743deb2a.  Can you check and make sure it works for you?

**Comment by Horray** [comment]
Thanks!
