### ISSUE TITLE
In a loop, toString('hex3') returns hex6 sometimes

### ISSUE THREAD

**Issue by z** [bgrins/TinyColor#119]
```
var i = 0;
var nextColor = '#f00';

while (i < 5) {

    nextColor = tinycolor(nextColor).spin(10).toString('hex3');
    console.log(nextColor);
    i++;

};
```

outputs:

```
#ff2b00
#f50
#ff8000
#fa0
#ffd500
```

It seems anything under ~20 for the value passed to spin() does this.

**Comment by bgrins** [comment]
Any color that cannot be represented with 3 characters will output as 6 characters when `.toString('hex3')` is called.  For instance `tinycolor("#abcdef").toString("hex3")` will return `#abcdef`.  But `tinycolor("#aabbcc").toString("hex3")` will return `#abc`
