### ISSUE TITLE
HEX8 format was changed in minor release

### ISSUE THREAD

**Issue by erlswtshrt** [bgrins/TinyColor#139]
I noticed that the HEX8 format was changed in the latest release (from ARGB to RGBA). This reflects the standard, but probably should have been pushed as a major release?

Also, Android uses ARGB while the standard is RGBA, so it might be useful to include functionality for both formats.

**Comment by bgrins** [comment]
> I noticed that the HEX8 format was changed in the latest release (from ARGB to RGBA). This reflects the standard, but probably should have been pushed as a major release?

Yeah that's a good point.  Although now that it's been done I don't think there's anything to do about it.

> Also, Android uses ARGB while the standard is RGBA, so it might be useful to include functionality for both formats.

I'm not  interested in keeping the old behavior as part of the main library (either as an arg to toHex8 or as a new function).  It could be created by a caller by doing toHex() and then moving the last 2 characters to the front.

**Comment by kaelig** [comment]
@bgrins Thank you for your answer, and for creating TinyColor, it's really awesome and we use it extensively in [salesforce-ux/theo](https://github.com/salesforce-ux/theo)!

I'd like to point out that Android is still using AARRGGBB as you can see in their documentation: https://developer.android.com/reference/android/graphics/Color.html

Unless I've missed an announcement on their part, this does not seem to be an "old behavior". It's a shame they don't use the RRGGBBAA standard, and as a result, there is such a thing as an "Hex 8 à la Android".

Fortunately their embedded browsers do support the CSS standard RRGGBBAA but the OS / Native part of Android will work with AARRGGBB.

I'd be curious to know your stance on this, and if it would make sense to have an argument such as `tinycolor("red").toHex8({ format: "aarrggbb" })` (that's something we'd use at Salesforce).

Considering this, I'd be happy to submit a pull request for it if this is something you'd see in the main library.
