### ISSUE TITLE
toRgbArray() method

### ISSUE THREAD

**Issue by dfcreative** [bgrins/TinyColor#140]
Hi @bgrins!

Maybe I don’t understand something, but is there a way to get array representation of rgb color?
Eg 

``` js
color('rgb(12, 12, 12)').someMagicReturningRgbArray();  //[12, 12, 12]
```

It is almost everyday use-case but I can’t figure out is there such method. If no - should I do a PR?

Thanks!

**Comment by thachhoang** [comment]
You can do that with the current API:
```js
var c = tinycolor('rgb(12, 12, 12)').toRgb();
[c.r, c.g, c.b]; // [12, 12, 12]
```
