### ISSUE TITLE
isValid() function returning true for invalid hsl or rgb colors

### ISSUE THREAD

**Issue by mburakerman** [bgrins/TinyColor#161]
Thanks for awesome library!

Theres is small issues about `isValid()` function.

Unless we don't write a letter,  `isValid()` function returns `true `for rgb and hsl colors.

` alert(tinycolor('hsla(642,14%,76%,1)').isValid())`

[jsfiddle](https://jsfiddle.net/oqjr12ah/)

**Comment by defue** [comment]
Also #fafa is treated as valid color while it is not. Version 1.4.1.

**Comment by whostolemyhat** [comment]
Hex colours with two hashes are also considered valid:

`tinycolor('##abc123').isValid() // true`

**Comment by nyteksf** [comment]
Hello. I've posted this related PR [here](https://github.com/bgrins/TinyColor/pull/166) for review, please. I was not able to reproduce the above mentioned double pound sign error with hex colors, but I did manage to address preventing multiple commas and choosing from without the valid range. Thanks for your time.
