### ISSUE TITLE
Inverse?

### ISSUE THREAD

**Issue by Noitidart** [bgrins/TinyColor#164]
Hi there,
I was wondering how to get the inverse of a color. I tried `color.spin(180).toHexString()` however this is not doing it.

Is it possible to set the indiviudal components on a color? Like I am trying to set the `blue` component: `color.setBlue(200)` or `color.setHue(...)`

Thanks

**Comment by colinkahn** [comment]
@Noitidart I had to do this today and wrote this function, which seems to work:

```
const inverseColor = (color) => {
  const rgb = tinycolor(color).toRgb();
  return tinycolor({
    r: 255 - rgb.r,
    g: 255 - rgb.g,
    b: 255 - rgb.b,
  }).toHexString();
};
```

**Comment by Noitidart** [comment]
Oh no way! It's that easy, thanks @colinkahn!!
