### ISSUE TITLE
v2: rename legacyRandom to trueRandom, and move it into random.ts

### ISSUE THREAD

**Issue by bgrins** [bgrins/TinyColor#182]
The new `random` function generates attractive random colors. `legacyRandom` generates actual random colors - so I think `trueRandom` or something like that would be a better name for it. Alternatively, we could expose it as an option to the `random` function.

It also seems like it'd be a better fit for the random module and not fromRatio.

**Comment by scttcper** [comment]
the new random has a full random, but the renaming and moving makes sense.

in the readme as
```ts
random({
  luminosity: 'random',
  hue: 'random',
});
```
