### ISSUE TITLE
Lightness of 1% returns white

### ISSUE THREAD

**Issue by octocat-1** [bgrins/TinyColor#200]
`tinycolor({ h:22, s:58, l:1 }).toHexString()` => Output: #ffffff

I would assume a HSL lightness of 1% would output a hex-string that is close to black. The HSL converter on W3Schools (https://www.w3schools.com/colors/colors_converter.asp) also shows the hexString is close to black (i.e. #040201)...

**Comment by dackmin** [comment]
If given an object, values are from 0 to 1, so 1 is 100%.
