### ISSUE TITLE
support esm package

### ISSUE THREAD

**Issue by vthinkxie** [bgrins/TinyColor#217]
To ensure the bundler can successfully optimize your application, avoid depending on CommonJS modules, and use ECMAScript module syntax in your entire application.

ref
https://web.dev/commonjs-larger-bundles

**Comment by lukasoppermann** [comment]
Exporting this package as an es6 module would be awesome. 🙏

**Comment by bgrins** [comment]
Thanks for filing this - ESM should be working in 1.5.0 on npm after #245. I've confirmed in a test repo at https://github.com/bgrins/test-tinycolor-upgrade.
