### ISSUE TITLE
Feature: include alpha in Hex

### ISSUE THREAD

**Issue by itta611** [bgrins/TinyColor#235]
Modern browsers allow to contain alpha values in Hex. (Ex. `rgba(0, 0, 0, 0.5)` = `#00000080`)
However,
```js
tinycolor('rgba(0, 0, 0, 0.3)').toHex()
```
will be `#000000`.

**Comment by kilobyte2007** [comment]
There is a `toHex8` for that already.

**Comment by itta611** [comment]
thanks.
