### ISSUE TITLE
why tinycolor({h: 0, s: 100,v: 0}).toHsv() result {h: 0, s: 0, v: 0} ?

### ISSUE THREAD

**Issue by otary** [bgrins/TinyColor#272]
why `tinycolor({h: 0, s: 100,v: 0}).toHsv()` result `{h: 0, s: 0, v: 0}` ?

**Comment by aiktb** [comment]
I encountered the same issue and it has troubled me for a long time. Have you found a solution?

**Comment by otary** [comment]
I added a layer of judgment on the outer layer instead of directly using tinycolor, code like this:
```
if (color.s === 100) {
    return {
        h: 0,
        s: 100,
        v: 0
    }
}
return tinycolor(color);
````
