### ISSUE TITLE
Consider talking with the owner of npm tinycolor to get his name

### ISSUE THREAD

**Issue by totty90** [bgrins/TinyColor#83]

**Comment by bgrins** [comment]
I would love to get the name, but it's actually downloaded way more than ours.  With all of the packages dependant on that, taking over that name would probably cause some real problems.

https://www.npmjs.com/package/tinycolor
https://www.npmjs.com/package/tinycolor2

**Comment by totty90** [comment]
I suppose is wrongly downloaded.. Try talking to the npm guys, because their lib does not have docs and IMO is missleading because intalling npm tinycolor I would expect this library and not the other. Look at the repo of their lib: https://github.com/einaros/tinycolor
