### ISSUE TITLE
Don't mutate input objects

### ISSUE THREAD

**Issue by benekastah** [bgrins/TinyColor#95]
Currently the tinycolor constructor actually modifies input objects:

```
var hsv = {h: 100, s: 0.5, v: 0.5};
tinycolor(hsv);
console.log(hsv);  // Object {h: 100, s: "50%", v: "50%"}
```

I spent a while trying to figure out why I was getting `NaN`s in my app :)

**Comment by bgrins** [comment]
Yeah, looks like `inputToRgb` should make a clone of the input if it's an object: https://github.com/bgrins/TinyColor/blob/f7cd274b12f0aaecb974270632b24d0200175b97/tinycolor.js#L300

**Comment by WickyNilliams** [comment]
Yes please. This makes the API very painful to use as it stands.

**Comment by Klortho** [comment]
+1
I was *shocked* to find that even `new tinycolor(old)` doesn't make a copy.

**Comment by cpsubrian** [comment]
👍  Ran into this and was majorly hard to track down what was breaking.

**Comment by bgrins** [comment]
Would anyone like to take this on?

**Comment by cpsubrian** [comment]
If I get a chance this weekend I'll work up a PR.

**Comment by bgrins** [comment]
> If I get a chance this weekend I'll work up a PR

thanks!

**Comment by bgrins** [comment]
Fixed by https://github.com/bgrins/TinyColor/pull/132

**Comment by bgrins** [comment]
Fixed by https://github.com/bgrins/TinyColor/pull/132
