### ISSUE TITLE
Getting wrong brightness values?

### ISSUE THREAD

**Issue by kevincannon** [bgrins/TinyColor#99]
I'm trying to sort colours by brightness, and getting unexpected results:

Here's the stripped down test code.
```
        var testYellow = tinycolor("#d6e44b");
        var testPink = tinycolor("#e491af");

        console.log("testYellow " + testYellow.getBrightness()); // outputs: 206.372
        console.log("testPink " + testPink.getBrightness());  // outputs: 173.237

        console.log("testYellow " + testYellow.getLuminance()); // outputs: 0.7029094646191199
        console.log("testPink " + testPink.getLuminance()); // outputs: 0.39839923662533866
```

The problem is, that Photoshop reports the brightness of Yellow to be: 89% and the Pink: 93%.

Visually, the pink looks lighter.

<img width="105" alt="screen shot 2015-08-11 at 23 07 18" src="https://cloud.githubusercontent.com/assets/5065238/9210642/c2e6be66-407d-11e5-8355-039a5b328d0c.png">

Is this a bug or am I doing something wrong?

**Comment by bgrins** [comment]
The brightness formula was taken from: http://www.w3.org/TR/AERT#color-contrast.  Specifically:
  
    Color brightness is determined by the following formula:
    ((Red value X 299) + (Green value X 587) + (Blue value X 114)) / 1000
    Note: This algorithm is taken from a formula for converting RGB values to YIQ values. This brightness value gives a perceived brightness for a color.

**Comment by bgrins** [comment]
According to that, this formula give a 'perceived brightness for a color' (specifically for accessibility guidelines), so we are just reporting the results.

**Comment by bgrins** [comment]
> The problem is, that Photoshop reports the brightness of Yellow to be: 89% and the Pink: 93%.

That must be reporting some other value of brightness - I'm not sure the details of what Photoshop is showing, but if there is a more correct value for 'brightness' then maybe we could rename our current `getBrightness()` to `getPerceivedBrightness()` and then swap in the new implementation.

**Comment by kevincannon** [comment]
Thanks for the reply and the info. I think that's probbaly the best algorithm to use. Perceived brightness is actually what people want most of the time. Still there's something wrong with that weighting. If I find something else, i'll let you know.
